[build]
  publish = "public"
  command = "# no build command needed"

[[redirects]]
  from = "/*"
  to = "/admin.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains" 